// Code generated by main. DO NOT EDIT.

package sese_035_002_09

import (
	"bytes"
	"encoding/xml"
	"time"
)

type ActiveCurrencyAndAmount struct {
	Value float64            `xml:",chardata"`
	Ccy   ActiveCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveCurrencyCode string

type ActiveOrHistoricCurrencyAndAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern [A-Z]{3,3}
type ActiveOrHistoricCurrencyCode string

type AdditionalParameters26 struct {
	PreConf        PreConfirmation1Code    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PreConf,omitempty"`
	PrtlSttlm      PartialSettlement2Code  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrtlSttlm,omitempty"`
	PrvsPrtlConfId RestrictedFINXMax16Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrvsPrtlConfId,omitempty"`
}

type AlternatePartyIdentification9 struct {
	IdTp    IdentificationType44Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IdTp"`
	Ctry    CountryCode                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ctry"`
	AltrnId RestrictedFINXMax30Text    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId"`
}

type AmountAndDirection19 struct {
	Amt    RestrictedFINActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Amt"`
	CdtDbt CreditDebitCode                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CdtDbt,omitempty"`
}

type AmountAndDirection44 struct {
	Amt                 ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Amt"`
	CdtDbtInd           CreditDebitCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CdtDbtInd,omitempty"`
	OrgnlCcyAndOrdrdAmt ActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OrgnlCcyAndOrdrdAmt,omitempty"`
	FXDtls              ForeignExchangeTerms23            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FXDtls,omitempty"`
}

type AmountAndDirection58 struct {
	Amt                 RestrictedFINActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Amt"`
	CdtDbtInd           CreditDebitCode                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CdtDbtInd,omitempty"`
	OrgnlCcyAndOrdrdAmt RestrictedFINActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OrgnlCcyAndOrdrdAmt,omitempty"`
	FXDtls              ForeignExchangeTerms27                         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FXDtls,omitempty"`
}

type AmountAndDirection59 struct {
	Amt       RestrictedFINActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Amt"`
	CdtDbtInd CreditDebitCode                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CdtDbtInd,omitempty"`
}

type AmountAndDirection96 struct {
	AcrdIntrstInd       bool                                           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AcrdIntrstInd,omitempty"`
	StmpDtyInd          bool                                           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StmpDtyInd,omitempty"`
	BrkrgAmtInd         bool                                           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 BrkrgAmtInd,omitempty"`
	RsrchFeeInd         bool                                           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RsrchFeeInd,omitempty"`
	Amt                 RestrictedFINActiveCurrencyAndAmount           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Amt"`
	CdtDbtInd           CreditDebitCode                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CdtDbtInd"`
	OrgnlCcyAndOrdrdAmt RestrictedFINActiveOrHistoricCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OrgnlCcyAndOrdrdAmt,omitempty"`
	FXDtls              ForeignExchangeTerms27                         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FXDtls,omitempty"`
	ValDt               DateAndDateTime2Choice                         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ValDt,omitempty"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type AnyBICDec2014Identifier string

// May be one of LAMI, NBOR, YBOR
type AutoBorrowing1Code string

type AutomaticBorrowing8Choice struct {
	Cd    AutoBorrowing1Code      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// Must match the pattern [A-Z0-9]{4,4}[A-Z]{2,2}[A-Z0-9]{2,2}([A-Z0-9]{3,3}){0,1}
type BICFIDec2014Identifier string

type BeneficialOwnership5Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ind"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of BLPA, BLCH
type BlockTrade1Code string

type BlockTrade5Choice struct {
	Cd    BlockTrade1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// Must match the pattern [A-Z]{6,6}
type CFIOct2015Identifier string

type CashAccountIdentification6Choice struct {
	IBAN  IBAN2007Identifier       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IBAN"`
	Prtry RestrictedFINX2Max34Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type CashParties38 struct {
	Dbtr    PartyIdentificationAndAccount177 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Dbtr,omitempty"`
	DbtrAgt PartyIdentificationAndAccount178 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DbtrAgt,omitempty"`
	Cdtr    PartyIdentificationAndAccount177 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cdtr,omitempty"`
	CdtrAgt PartyIdentificationAndAccount178 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CdtrAgt,omitempty"`
	Intrmy  PartyIdentificationAndAccount178 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Intrmy,omitempty"`
}

// May be one of GROS, NETS
type CashSettlementSystem2Code string

type CashSettlementSystem5Choice struct {
	Cd    CashSettlementSystem2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type CentralCounterPartyEligibility5Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ind"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type ClassificationType33Choice struct {
	ClssfctnFinInstrm CFIOct2015Identifier    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ClssfctnFinInstrm"`
	AltrnClssfctn     GenericIdentification86 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnClssfctn"`
}

type Counterparty14Choice struct {
	Sellr PartyIdentificationAndAccount176 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Sellr"`
	Buyr  PartyIdentificationAndAccount176 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Buyr"`
}

// Must match the pattern [A-Z]{2,2}
type CountryCode string

// May be one of CRDT, DBIT
type CreditDebitCode string

type DateAndDateTime2Choice struct {
	Dt   ISODate     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Dt"`
	DtTm ISODateTime `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DtTm"`
}

type DateCode32Choice struct {
	Cd    DateType5Code           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of VARI
type DateType3Code string

// May be one of OPEN
type DateType5Code string

// May be one of FREE, APMT
type DeliveryReceiptType2Code string

type Document struct {
	SctiesFincgConf SecuritiesFinancingConfirmation002V09 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SctiesFincgConf"`
}

// May be one of ELIG, RETL, PROF
type Eligibility1Code string

// May be one of YEAR, MNTH, QUTR, SEMI, WEEK
type EventFrequency3Code string

// Must match the pattern [0-9]{3}
type Exact3NumericText string

// Must match the pattern [a-zA-Z0-9]{4}
type Exact4AlphaNumericText string

// Must match the pattern [0-9]{4}
type Exact4NumericText string

// Must be at least 1 items long
type ExternalFinancialInstrumentIdentificationType1Code string

type FinancialInstrumentAttributes97 struct {
	PlcOfListg             MarketIdentification4Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PlcOfListg,omitempty"`
	DayCntBsis             InterestComputationMethodFormat5Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DayCntBsis,omitempty"`
	RegnForm               FormOfSecurity7Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RegnForm,omitempty"`
	PmtFrqcy               Frequency27Choice                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PmtFrqcy,omitempty"`
	PmtSts                 SecuritiesPaymentStatus6Choice         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PmtSts,omitempty"`
	VarblRateChngFrqcy     Frequency27Choice                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 VarblRateChngFrqcy,omitempty"`
	ClssfctnTp             ClassificationType33Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ClssfctnTp,omitempty"`
	OptnStyle              OptionStyle9Choice                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OptnStyle,omitempty"`
	OptnTp                 OptionType7Choice                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OptnTp,omitempty"`
	DnmtnCcy               ActiveOrHistoricCurrencyCode           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DnmtnCcy,omitempty"`
	CpnDt                  ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CpnDt,omitempty"`
	XpryDt                 ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 XpryDt,omitempty"`
	FltgRateFxgDt          ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FltgRateFxgDt,omitempty"`
	MtrtyDt                ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MtrtyDt,omitempty"`
	IsseDt                 ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IsseDt,omitempty"`
	NxtCllblDt             ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NxtCllblDt,omitempty"`
	PutblDt                ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PutblDt,omitempty"`
	DtdDt                  ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DtdDt,omitempty"`
	FrstPmtDt              ISODate                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FrstPmtDt,omitempty"`
	PrvsFctr               float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrvsFctr,omitempty"`
	CurFctr                float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CurFctr,omitempty"`
	NxtFctr                float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NxtFctr,omitempty"`
	IntrstRate             float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IntrstRate,omitempty"`
	YldToMtrtyRate         float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 YldToMtrtyRate,omitempty"`
	NxtIntrstRate          float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NxtIntrstRate,omitempty"`
	IndxRateBsis           float64                                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IndxRateBsis,omitempty"`
	CpnAttchdNb            Number23Choice                         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CpnAttchdNb,omitempty"`
	PoolNb                 GenericIdentification39                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PoolNb,omitempty"`
	VarblRateInd           bool                                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 VarblRateInd,omitempty"`
	CllblInd               bool                                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CllblInd,omitempty"`
	PutblInd               bool                                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PutblInd,omitempty"`
	MktOrIndctvPric        PriceType5Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MktOrIndctvPric,omitempty"`
	ExrcPric               Price3                                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ExrcPric,omitempty"`
	SbcptPric              Price3                                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SbcptPric,omitempty"`
	ConvsPric              Price3                                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ConvsPric,omitempty"`
	StrkPric               Price3                                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StrkPric,omitempty"`
	MinNmnlQty             FinancialInstrumentQuantity15Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MinNmnlQty,omitempty"`
	CtrctSz                FinancialInstrumentQuantity15Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CtrctSz,omitempty"`
	UndrlygFinInstrmId     []SecurityIdentification20             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 UndrlygFinInstrmId,omitempty"`
	FinInstrmAttrAddtlDtls RestrictedFINXMax350Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FinInstrmAttrAddtlDtls,omitempty"`
}

type FinancialInstrumentQuantity15Choice struct {
	Unit     float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Unit"`
	FaceAmt  float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FaceAmt"`
	AmtsdVal float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AmtsdVal"`
}

type ForeignExchangeTerms23 struct {
	UnitCcy  ActiveCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 UnitCcy"`
	QtdCcy   ActiveCurrencyCode      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 QtdCcy"`
	XchgRate float64                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 XchgRate"`
	RsltgAmt ActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RsltgAmt"`
}

type ForeignExchangeTerms27 struct {
	UnitCcy  ActiveCurrencyCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 UnitCcy"`
	QtdCcy   ActiveCurrencyCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 QtdCcy"`
	XchgRate float64                              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 XchgRate"`
	RsltgAmt RestrictedFINActiveCurrencyAndAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RsltgAmt"`
}

// May be one of BEAR, REGD
type FormOfSecurity1Code string

type FormOfSecurity7Choice struct {
	Cd    FormOfSecurity1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type Frequency27Choice struct {
	Cd    EventFrequency3Code     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type GenericIdentification18 struct {
	Id      RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	SchmeNm Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SchmeNm,omitempty"`
	Issr    Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Issr,omitempty"`
}

type GenericIdentification39 struct {
	Id   RestrictedFINMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	Issr RestrictedFINMax8Text  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Issr,omitempty"`
}

type GenericIdentification47 struct {
	Id      Exact4AlphaNumericText `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	Issr    Max4AlphaNumericText   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Issr"`
	SchmeNm Max4AlphaNumericText   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SchmeNm,omitempty"`
}

type GenericIdentification84 struct {
	Id      RestrictedFINXMax34Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	Issr    Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Issr"`
	SchmeNm Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SchmeNm,omitempty"`
}

type GenericIdentification85 struct {
	Tp GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Tp"`
	Id RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id,omitempty"`
}

type GenericIdentification86 struct {
	Id      RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	Issr    Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Issr"`
	SchmeNm Max4AlphaNumericText    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SchmeNm,omitempty"`
}

// Must match the pattern [A-Z]{2,2}[0-9]{2,2}[a-zA-Z0-9]{1,30}
type IBAN2007Identifier string

// Must match the pattern [A-Z]{2,2}[A-Z0-9]{9,9}[0-9]{1,1}
type ISINOct2015Identifier string

type ISODate time.Time

func (t *ISODate) UnmarshalText(text []byte) error {
	return (*xsdDate)(t).UnmarshalText(text)
}
func (t ISODate) MarshalText() ([]byte, error) {
	return xsdDate(t).MarshalText()
}

type ISODateTime time.Time

func (t *ISODateTime) UnmarshalText(text []byte) error {
	return (*xsdDateTime)(t).UnmarshalText(text)
}
func (t ISODateTime) MarshalText() ([]byte, error) {
	return xsdDateTime(t).MarshalText()
}

type IdentificationSource4Choice struct {
	Cd    ExternalFinancialInstrumentIdentificationType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry RestrictedFINExact2Text                            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type IdentificationType44Choice struct {
	Cd    TypeOfIdentification1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of A001, A002, A003, A004, A005, A006, A007, A008, A009, A010, A011, A012, A013, A014, NARR
type InterestComputationMethod2Code string

type InterestComputationMethodFormat5Choice struct {
	Cd    InterestComputationMethod2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type InvestorCapacity5Choice struct {
	Cd    Eligibility1Code        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// Must match the pattern [A-Z0-9]{18,18}[0-9]{2,2}
type LEIIdentifier string

// May be one of FRAN
type LegalFramework1Code string

type LegalFramework4Choice struct {
	Cd    LegalFramework1Code     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// Must match the pattern [A-Z0-9]{4,4}
type MICIdentifier string

// May be one of CLNT, MAKT
type MarketClientSide1Code string

type MarketClientSide7Choice struct {
	Cd    MarketClientSide1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type MarketIdentification2Choice struct {
	MktIdrCd MICIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MktIdrCd"`
	Desc     RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Desc"`
}

type MarketIdentification4Choice struct {
	MktIdrCd MICIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MktIdrCd"`
	Desc     RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Desc"`
}

type MarketIdentification90 struct {
	Id MarketIdentification2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id,omitempty"`
	Tp MarketType16Choice          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Tp"`
}

type MarketType16Choice struct {
	Cd    MarketType2Code         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of PRIM, SECM, OTCO, VARI, EXCH
type MarketType2Code string

// Must be at least 1 items long
type Max16Text string

// Must be at least 1 items long
type Max350Text string

// Must match the pattern [a-zA-Z0-9]{1,4}
type Max4AlphaNumericText string

// Must be at least 1 items long
type Max70Text string

type NameAndAddress12 struct {
	Nm RestrictedFINXMax140Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Nm"`
}

type NettingEligibility5Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ind"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type Number23Choice struct {
	Shrt Exact3NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Shrt"`
	Lng  GenericIdentification18 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Lng"`
}

// May be one of AMER, EURO
type OptionStyle2Code string

type OptionStyle9Choice struct {
	Cd    OptionStyle2Code        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of CALL, PUTO
type OptionType1Code string

type OptionType7Choice struct {
	Cd    OptionType1Code         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type OriginalAndCurrentQuantities4 struct {
	FaceAmt  float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FaceAmt"`
	AmtsdVal float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AmtsdVal"`
}

// May be one of SINT, MLTF, RMKT, MKTM, INVE, TAGT
type OriginatorRole2Code string

type OtherAmounts42 struct {
	AcrdIntrstAmt   AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AcrdIntrstAmt,omitempty"`
	ChrgsFees       AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ChrgsFees,omitempty"`
	CtryNtlFdrlTax  AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CtryNtlFdrlTax,omitempty"`
	TradAmt         AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TradAmt,omitempty"`
	ExctgBrkrAmt    AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ExctgBrkrAmt,omitempty"`
	IsseDscntAllwnc AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IsseDscntAllwnc,omitempty"`
	PmtLevyTax      AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PmtLevyTax,omitempty"`
	LclTax          AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LclTax,omitempty"`
	LclBrkrComssn   AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LclBrkrComssn,omitempty"`
	Mrgn            AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Mrgn,omitempty"`
	Othr            AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Othr,omitempty"`
	RgltryAmt       AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RgltryAmt,omitempty"`
	ShppgAmt        AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ShppgAmt,omitempty"`
	SpclCncssn      AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SpclCncssn,omitempty"`
	StmpDty         AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StmpDty,omitempty"`
	StockXchgTax    AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StockXchgTax,omitempty"`
	TrfTax          AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TrfTax,omitempty"`
	TxTax           AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TxTax,omitempty"`
	ValAddedTax     AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ValAddedTax,omitempty"`
	WhldgTax        AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 WhldgTax,omitempty"`
	NetGnLoss       AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NetGnLoss,omitempty"`
	CsmptnTax       AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CsmptnTax,omitempty"`
	AcrdCptlstnAmt  AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AcrdCptlstnAmt,omitempty"`
	BookVal         AmountAndDirection58 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 BookVal,omitempty"`
	RsrchFee        AmountAndDirection44 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RsrchFee,omitempty"`
}

type OtherIdentification2 struct {
	Id  RestrictedFINXMax31Text     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	Sfx Max16Text                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Sfx,omitempty"`
	Tp  IdentificationSource4Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Tp"`
}

type OtherParties35 struct {
	Invstr         []PartyIdentificationAndAccount179 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Invstr,omitempty"`
	QlfdFrgnIntrmy PartyIdentificationAndAccount180   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 QlfdFrgnIntrmy,omitempty"`
	StockXchg      PartyIdentificationAndAccount181   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StockXchg,omitempty"`
	TradRgltr      PartyIdentificationAndAccount181   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TradRgltr,omitempty"`
	TrptyAgt       PartyIdentificationAndAccount180   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TrptyAgt,omitempty"`
	Brkr           PartyIdentificationAndAccount180   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Brkr,omitempty"`
}

// May be one of A144, NRST, RSTR
type OwnershipLegalRestrictions1Code string

// May be one of PAIN, PARC
type PartialSettlement2Code string

type PartyIdentification136Choice struct {
	AnyBIC  AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AnyBIC"`
	PrtryId GenericIdentification84 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrtryId"`
}

type PartyIdentification137Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AnyBIC"`
	PrtryId  GenericIdentification84 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrtryId"`
	NmAndAdr NameAndAddress12        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NmAndAdr"`
}

type PartyIdentification145Choice struct {
	AnyBIC   AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AnyBIC"`
	NmAndAdr NameAndAddress12        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NmAndAdr"`
	Ctry     CountryCode             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ctry"`
}

type PartyIdentification147Choice struct {
	BICFI    BICFIDec2014Identifier  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 BICFI"`
	NmAndAdr NameAndAddress12        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NmAndAdr"`
	PrtryId  GenericIdentification84 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrtryId"`
}

type PartyIdentification156 struct {
	Id  PartyIdentification136Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
}

type PartyIdentification157 struct {
	Id  PartyIdentification137Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI LEIIdentifier                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
}

type PartyIdentification162 struct {
	Id       PartyIdentification145Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI      LEIIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
	AltrnId  AlternatePartyIdentification9 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId,omitempty"`
	PrcgDt   DateAndDateTime2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrcgDt,omitempty"`
	PrcgId   RestrictedFINXMax16Text       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrcgId,omitempty"`
	AddtlInf PartyTextInformation3         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlInf,omitempty"`
}

type PartyIdentificationAndAccount176 struct {
	Id        PartyIdentification137Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI       LEIIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
	AltrnId   AlternatePartyIdentification9 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId,omitempty"`
	SfkpgAcct SecuritiesAccount30           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgAcct,omitempty"`
	PrcgDt    DateAndDateTime2Choice        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrcgDt,omitempty"`
	PrcgId    RestrictedFINXMax16Text       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrcgId,omitempty"`
	AddtlInf  PartyTextInformation3         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlInf,omitempty"`
}

type PartyIdentificationAndAccount177 struct {
	Id         PartyIdentification137Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI        LEIIdentifier                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
	AltrnId    AlternatePartyIdentification9    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId,omitempty"`
	CshAcct    CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CshAcct,omitempty"`
	ChrgsAcct  CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ChrgsAcct,omitempty"`
	ComssnAcct CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ComssnAcct,omitempty"`
	TaxAcct    CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TaxAcct,omitempty"`
	AddtlInf   PartyTextInformation4            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlInf,omitempty"`
}

type PartyIdentificationAndAccount178 struct {
	Id         PartyIdentification147Choice     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI        LEIIdentifier                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
	AltrnId    AlternatePartyIdentification9    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId,omitempty"`
	CshAcct    CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CshAcct,omitempty"`
	ChrgsAcct  CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ChrgsAcct,omitempty"`
	ComssnAcct CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ComssnAcct,omitempty"`
	TaxAcct    CashAccountIdentification6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TaxAcct,omitempty"`
	AddtlInf   PartyTextInformation4            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlInf,omitempty"`
}

type PartyIdentificationAndAccount179 struct {
	Id        PartyIdentification137Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id,omitempty"`
	LEI       LEIIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
	AltrnId   AlternatePartyIdentification9 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId,omitempty"`
	Ntlty     CountryCode                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ntlty,omitempty"`
	SfkpgAcct RestrictedFINXMax35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgAcct,omitempty"`
	PrcgId    RestrictedFINXMax16Text       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrcgId,omitempty"`
	AddtlInf  PartyTextInformation3         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlInf,omitempty"`
}

type PartyIdentificationAndAccount180 struct {
	Id        PartyIdentification137Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI       LEIIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
	AltrnId   AlternatePartyIdentification9 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId,omitempty"`
	SfkpgAcct RestrictedFINXMax35Text       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgAcct,omitempty"`
	PrcgId    RestrictedFINXMax16Text       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrcgId,omitempty"`
	AddtlInf  PartyTextInformation3         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlInf,omitempty"`
}

type PartyIdentificationAndAccount181 struct {
	Id       PartyIdentification137Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	LEI      LEIIdentifier                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
	AltrnId  AlternatePartyIdentification9 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AltrnId,omitempty"`
	PrcgId   RestrictedFINXMax16Text       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrcgId,omitempty"`
	AddtlInf PartyTextInformation3         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlInf,omitempty"`
}

type PartyTextInformation3 struct {
	DclrtnDtls  RestrictedFINXMax350Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DclrtnDtls,omitempty"`
	PtyCtctDtls RestrictedFINXMax140Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PtyCtctDtls,omitempty"`
	RegnDtls    RestrictedFINXMax350Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RegnDtls,omitempty"`
}

type PartyTextInformation4 struct {
	DclrtnDtls  RestrictedFINXMax350Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DclrtnDtls,omitempty"`
	PtyCtctDtls RestrictedFINXMax140Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PtyCtctDtls,omitempty"`
}

type PlaceOfClearingIdentification2 struct {
	Id  AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id,omitempty"`
	LEI LEIIdentifier           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
}

type PlaceOfTradeIdentification2 struct {
	MktTpAndId MarketIdentification90 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MktTpAndId,omitempty"`
	LEI        LEIIdentifier          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
}

// May be one of PRCA, PRSE
type PreConfirmation1Code string

type Price3 struct {
	Tp  YieldedOrValueType1Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Tp"`
	Val PriceRateOrAmount1Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Val"`
}

type PriceRateOrAmount1Choice struct {
	Rate float64                                                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Rate"`
	Amt  RestrictedFINActiveOrHistoricCurrencyAnd13DecimalAmount `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Amt"`
}

type PriceType5Choice struct {
	Mkt    Price3 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Mkt"`
	Indctv Price3 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Indctv"`
}

// May be one of DISC, PREM, PARV
type PriceValueType1Code string

type PriorityNumeric5Choice struct {
	Nmrc  Exact4NumericText       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Nmrc"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type Quantity10Choice struct {
	Qty             FinancialInstrumentQuantity15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Qty"`
	OrgnlAndCurFace OriginalAndCurrentQuantities4       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OrgnlAndCurFace"`
}

type QuantityAndAccount85 struct {
	SttldQty         Quantity10Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttldQty"`
	PrevslySttldQty  FinancialInstrumentQuantity15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrevslySttldQty,omitempty"`
	RmngToBeSttldQty FinancialInstrumentQuantity15Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RmngToBeSttldQty,omitempty"`
	PrevslySttldAmt  AmountAndDirection19                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrevslySttldAmt,omitempty"`
	RmngToBeSttldAmt AmountAndDirection19                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RmngToBeSttldAmt,omitempty"`
	AcctOwnr         PartyIdentification156              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AcctOwnr,omitempty"`
	SfkpgAcct        SecuritiesAccount30                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgAcct"`
	CshAcct          CashAccountIdentification6Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CshAcct,omitempty"`
	SfkpgPlc         SafeKeepingPlace4                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgPlc,omitempty"`
}

type Rate2 struct {
	Sgn  bool    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Sgn,omitempty"`
	Rate float64 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Rate"`
}

type RateName2 struct {
	Issr   RestrictedFINXMax8Text  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Issr,omitempty"`
	RateNm RestrictedFINXMax24Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RateNm"`
}

type RateOrName2Choice struct {
	Rate   Rate2     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Rate"`
	RateNm RateName2 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RateNm"`
}

// May be one of FIXE, FORF, VARI
type RateType1Code string

type RateType67Choice struct {
	Cd    RateType1Code           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of DELI, RECE
type ReceiveDelivery1Code string

type Reporting11Choice struct {
	Cd    Reporting3Code          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of BYIY, DEFR, REGU, STEX
type Reporting3Code string

type RestrictedFINActiveCurrencyAndAmount struct {
	Value float64            `xml:",chardata"`
	Ccy   ActiveCurrencyCode `xml:"Ccy,attr"`
}

type RestrictedFINActiveOrHistoricCurrencyAnd13DecimalAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

type RestrictedFINActiveOrHistoricCurrencyAndAmount struct {
	Value float64                      `xml:",chardata"`
	Ccy   ActiveOrHistoricCurrencyCode `xml:"Ccy,attr"`
}

// Must match the pattern XX|TS
type RestrictedFINExact2Text string

// Must match the pattern ([^/]+/)+([^/]+)|([^/]*)
type RestrictedFINMax30Text string

// Must match the pattern ([^/]+/)+([^/]+)|([^/]*)
type RestrictedFINMax8Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.,'\+ ]{1,34}
type RestrictedFINX2Max34Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.\n\r,'\+ ]{1,140}
type RestrictedFINXMax140Text string

// Must match the pattern ([0-9a-zA-Z\-\?:\(\)\.,'\+ ]([0-9a-zA-Z\-\?:\(\)\.,'\+ ]*(/[0-9a-zA-Z\-\?:\(\)\.,'\+ ])?)*)
type RestrictedFINXMax16Text string

// Must match the pattern ([0-9a-zA-Z\-\?:\(\)\.,'\+ ]([0-9a-zA-Z\-\?:\(\)\.,'\+ ]*(/[0-9a-zA-Z\-\?:\(\)\.,'\+ ])?)*)
type RestrictedFINXMax24Text string

// Must match the pattern ([0-9a-zA-Z\-\?:\(\)\.,'\+ ]([0-9a-zA-Z\-\?:\(\)\.,'\+ ]*(/[0-9a-zA-Z\-\?:\(\)\.,'\+ ])?)*)
type RestrictedFINXMax30Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.,'\+ ]{1,31}
type RestrictedFINXMax31Text string

// Must match the pattern ([0-9a-zA-Z\-\?:\(\)\.,'\+ ]([0-9a-zA-Z\-\?:\(\)\.,'\+ ]*(/[0-9a-zA-Z\-\?:\(\)\.,'\+ ])?)*)
type RestrictedFINXMax34Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.\n\r,'\+ ]{1,350}
type RestrictedFINXMax350Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.,'\+ ]{1,35}
type RestrictedFINXMax35Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.,'\+ ]{1,52}
type RestrictedFINXMax52Text string

// Must match the pattern [0-9a-zA-Z/\-\?:\(\)\.,'\+ ]{1,8}
type RestrictedFINXMax8Text string

type Restriction6Choice struct {
	Cd    OwnershipLegalRestrictions1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type RevaluationIndicator4Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ind"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type SafeKeepingPlace4 struct {
	SfkpgPlcFrmt SafekeepingPlaceFormat39Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgPlcFrmt,omitempty"`
	LEI          LEIIdentifier                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LEI,omitempty"`
}

// May be one of CUST, ICSD, NCSD, SHHE
type SafekeepingPlace1Code string

// May be one of SHHE
type SafekeepingPlace3Code string

type SafekeepingPlaceFormat39Choice struct {
	Id      SafekeepingPlaceTypeAndText15          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	Ctry    CountryCode                            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ctry"`
	TpAndId SafekeepingPlaceTypeAndIdentification1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TpAndId"`
	Prtry   GenericIdentification85                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type SafekeepingPlaceTypeAndIdentification1 struct {
	SfkpgPlcTp SafekeepingPlace1Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgPlcTp"`
	Id         AnyBICDec2014Identifier `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
}

type SafekeepingPlaceTypeAndText15 struct {
	SfkpgPlcTp SafekeepingPlace3Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SfkpgPlcTp"`
	Id         RestrictedFINXMax30Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id,omitempty"`
}

type SecuritiesAccount30 struct {
	Id RestrictedFINXMax35Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Id"`
	Tp GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Tp,omitempty"`
	Nm Max70Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Nm,omitempty"`
}

type SecuritiesFinancingConfirmation002V09 struct {
	TxIdDtls          TransactionTypeAndAdditionalParameters19 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TxIdDtls"`
	AddtlParams       AdditionalParameters26                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AddtlParams,omitempty"`
	TradDtls          SecuritiesTradeDetails101                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TradDtls"`
	FinInstrmId       SecurityIdentification20                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FinInstrmId"`
	FinInstrmAttrbts  FinancialInstrumentAttributes97          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FinInstrmAttrbts,omitempty"`
	QtyAndAcctDtls    QuantityAndAccount85                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 QtyAndAcctDtls"`
	SctiesFincgDtls   SecuritiesFinancingTransactionDetails46  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SctiesFincgDtls,omitempty"`
	StgSttlmInstrDtls StandingSettlementInstruction17          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StgSttlmInstrDtls,omitempty"`
	SttlmParams       SettlementDetails151                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttlmParams,omitempty"`
	DlvrgSttlmPties   SettlementParties81                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DlvrgSttlmPties,omitempty"`
	RcvgSttlmPties    SettlementParties81                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RcvgSttlmPties,omitempty"`
	CshPties          CashParties38                            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CshPties,omitempty"`
	SttldAmt          AmountAndDirection96                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttldAmt,omitempty"`
	OthrAmts          OtherAmounts42                           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OthrAmts,omitempty"`
	OthrBizPties      OtherParties35                           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OthrBizPties,omitempty"`
	SplmtryData       []SupplementaryData1                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SplmtryData,omitempty"`
}

type SecuritiesFinancingTransactionDetails46 struct {
	SctiesFincgTradId     RestrictedFINXMax52Text                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SctiesFincgTradId,omitempty"`
	ClsgLegId             RestrictedFINXMax16Text                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ClsgLegId,omitempty"`
	TermntnDt             TerminationDate7Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TermntnDt,omitempty"`
	RateChngDt            DateAndDateTime2Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RateChngDt,omitempty"`
	EarlstCallBckDt       DateAndDateTime2Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 EarlstCallBckDt,omitempty"`
	ComssnClctnDt         DateAndDateTime2Choice                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ComssnClctnDt,omitempty"`
	RateTp                RateType67Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RateTp,omitempty"`
	Rvaltn                RevaluationIndicator4Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Rvaltn,omitempty"`
	LglFrmwk              LegalFramework4Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LglFrmwk,omitempty"`
	IntrstCmptnMtd        InterestComputationMethodFormat5Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IntrstCmptnMtd,omitempty"`
	MtrtyDtMod            bool                                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MtrtyDtMod,omitempty"`
	IntrstPmt             bool                                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 IntrstPmt,omitempty"`
	VarblRateSpprt        RateName2                              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 VarblRateSpprt,omitempty"`
	RpRate                Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 RpRate,omitempty"`
	StockLnMrgn           Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StockLnMrgn,omitempty"`
	SctiesHrcut           Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SctiesHrcut,omitempty"`
	ChrgsRate             Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ChrgsRate,omitempty"`
	PricgRate             RateOrName2Choice                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PricgRate,omitempty"`
	Sprd                  Rate2                                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Sprd,omitempty"`
	TxCallDely            Exact3NumericText                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TxCallDely,omitempty"`
	TtlNbOfCollInstrs     Exact3NumericText                      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TtlNbOfCollInstrs,omitempty"`
	DealAmt               AmountAndDirection59                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DealAmt,omitempty"`
	AcrdIntrstAmt         AmountAndDirection59                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AcrdIntrstAmt,omitempty"`
	FrftAmt               AmountAndDirection59                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FrftAmt,omitempty"`
	PrmAmt                AmountAndDirection59                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrmAmt,omitempty"`
	TermntnAmtPerPcOfColl AmountAndDirection59                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TermntnAmtPerPcOfColl,omitempty"`
	TermntnTxAmt          AmountAndDirection59                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TermntnTxAmt,omitempty"`
	ScndLegNrrtv          RestrictedFINXMax140Text               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ScndLegNrrtv,omitempty"`
}

// May be one of REPU, RVPO, SECB, SECL, BSBK, SBBK
type SecuritiesFinancingTransactionType2Code string

// May be one of FULL, NILL, PART
type SecuritiesPaymentStatus1Code string

type SecuritiesPaymentStatus6Choice struct {
	Cd    SecuritiesPaymentStatus1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type SecuritiesRTGS5Choice struct {
	Ind   bool                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Ind"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type SecuritiesTradeDetails101 struct {
	PlcOfTrad               PlaceOfTradeIdentification2        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PlcOfTrad,omitempty"`
	PlcOfClr                PlaceOfClearingIdentification2     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PlcOfClr,omitempty"`
	TradDt                  TradeDate9Choice                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TradDt,omitempty"`
	SttlmDt                 SettlementDate20Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttlmDt,omitempty"`
	FctvSttlmDt             SettlementDate22Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FctvSttlmDt"`
	DealPric                Price3                             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DealPric,omitempty"`
	Rptg                    []Reporting11Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Rptg,omitempty"`
	NbOfDaysAcrd            float64                            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NbOfDaysAcrd,omitempty"`
	TradTxCond              []TradeTransactionCondition6Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TradTxCond,omitempty"`
	InvstrCpcty             InvestorCapacity5Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 InvstrCpcty,omitempty"`
	TradOrgtrRole           TradeOriginator4Choice             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TradOrgtrRole,omitempty"`
	SttlmInstrPrcgAddtlDtls RestrictedFINXMax350Text           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttlmInstrPrcgAddtlDtls,omitempty"`
	FxAddtlDtls             RestrictedFINXMax350Text           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 FxAddtlDtls,omitempty"`
}

type SecurityIdentification20 struct {
	ISIN   ISINOct2015Identifier    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ISIN,omitempty"`
	OthrId []OtherIdentification2   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OthrId,omitempty"`
	Desc   RestrictedFINXMax140Text `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Desc,omitempty"`
}

type SettlementDate20Choice struct {
	Dt   DateAndDateTime2Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Dt"`
	DtCd SettlementDateCode9Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DtCd"`
}

type SettlementDate22Choice struct {
	Dt   DateAndDateTime2Choice  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Dt"`
	DtCd GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DtCd"`
}

// May be one of WISS
type SettlementDate4Code string

type SettlementDateCode9Choice struct {
	Cd    SettlementDate4Code     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type SettlementDetails151 struct {
	Prty           PriorityNumeric5Choice                   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prty,omitempty"`
	SttlmTxCond    []SettlementTransactionCondition22Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttlmTxCond,omitempty"`
	SttlgCpcty     SettlingCapacity8Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttlgCpcty,omitempty"`
	StmpDtyTaxBsis GenericIdentification47                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 StmpDtyTaxBsis,omitempty"`
	SctiesRTGS     SecuritiesRTGS5Choice                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SctiesRTGS,omitempty"`
	BnfclOwnrsh    BeneficialOwnership5Choice               `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 BnfclOwnrsh,omitempty"`
	CshClrSys      CashSettlementSystem5Choice              `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CshClrSys,omitempty"`
	TaxCpcty       TaxCapacityParty5Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 TaxCpcty,omitempty"`
	MktClntSd      MarketClientSide7Choice                  `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 MktClntSd,omitempty"`
	BlckTrad       BlockTrade5Choice                        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 BlckTrad,omitempty"`
	LglRstrctns    Restriction6Choice                       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 LglRstrctns,omitempty"`
	SttlmSysMtd    SettlementSystemMethod5Choice            `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttlmSysMtd,omitempty"`
	NetgElgblty    NettingEligibility5Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 NetgElgblty,omitempty"`
	CCPElgblty     CentralCounterPartyEligibility5Choice    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CCPElgblty,omitempty"`
	AutomtcBrrwg   AutomaticBorrowing8Choice                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AutomtcBrrwg,omitempty"`
	PrtlSttlmInd   SettlementTransactionCondition5Code      `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PrtlSttlmInd,omitempty"`
	ElgblForColl   bool                                     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ElgblForColl,omitempty"`
}

type SettlementParties81 struct {
	Dpstry PartyIdentification162           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Dpstry,omitempty"`
	Pty1   PartyIdentificationAndAccount176 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Pty1,omitempty"`
	Pty2   PartyIdentificationAndAccount176 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Pty2,omitempty"`
	Pty3   PartyIdentificationAndAccount176 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Pty3,omitempty"`
	Pty4   PartyIdentificationAndAccount176 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Pty4,omitempty"`
	Pty5   PartyIdentificationAndAccount176 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Pty5,omitempty"`
}

// May be one of INTE, BRKR, VEND
type SettlementStandingInstructionDatabase1Code string

type SettlementStandingInstructionDatabase5Choice struct {
	Cd    SettlementStandingInstructionDatabase1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of NSET, YSET
type SettlementSystemMethod1Code string

type SettlementSystemMethod5Choice struct {
	Cd    SettlementSystemMethod1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type SettlementTransactionCondition22Choice struct {
	Cd    SettlementTransactionCondition6Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47             `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of PART, NPAR, PARC, PARQ
type SettlementTransactionCondition5Code string

// May be one of ASGN, BUTC, CLEN, DIRT, DLWM, DRAW, EXER, FRCL, KNOC, PHYS, RESI, SHOR, SPDL, SPST, EXPI, PENS, UNEX, TRIP, NOMC, TRAN, RHYP, ADEA
type SettlementTransactionCondition6Code string

// May be one of SAGE, CUST, SPRI, RISP
type SettlingCapacity2Code string

type SettlingCapacity8Choice struct {
	Cd    SettlingCapacity2Code   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type StandingSettlementInstruction17 struct {
	SttlmStgInstrDB     SettlementStandingInstructionDatabase5Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SttlmStgInstrDB"`
	CtrPty              Counterparty14Choice                         `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CtrPty"`
	Vndr                PartyIdentification157                       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Vndr,omitempty"`
	OthrDlvrgSttlmPties SettlementParties81                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OthrDlvrgSttlmPties,omitempty"`
	OthrRcvgSttlmPties  SettlementParties81                          `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 OthrRcvgSttlmPties,omitempty"`
}

type SupplementaryData1 struct {
	PlcAndNm Max350Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PlcAndNm,omitempty"`
	Envlp    SupplementaryDataEnvelope1 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Envlp"`
}

type SupplementaryDataEnvelope1 struct {
	Item string `xml:",any"`
}

type TaxCapacityParty5Choice struct {
	Cd    TaxLiability1Code       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of PRIN, AGEN
type TaxLiability1Code string

type TerminationDate7Choice struct {
	Dt DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Dt"`
	Cd DateCode32Choice       `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
}

type TradeDate9Choice struct {
	Dt   DateAndDateTime2Choice `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Dt"`
	DtCd TradeDateCode4Choice   `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 DtCd"`
}

type TradeDateCode4Choice struct {
	Cd    DateType3Code           `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type TradeOriginator4Choice struct {
	Cd    OriginatorRole2Code     `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

// May be one of CBNS, XBNS, CCPN, XCPN, CDIV, XDIV, CRTS, XRTS, CWAR, XWAR, SPCU, SPEX, GTDL, BCRO, BCRP, BCFD, BCBL, BCBN, MAPR, NEGO, NMPR, BCPD
type TradeTransactionCondition4Code string

type TradeTransactionCondition6Choice struct {
	Cd    TradeTransactionCondition4Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Cd"`
	Prtry GenericIdentification47        `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Prtry"`
}

type TransactionTypeAndAdditionalParameters19 struct {
	AcctOwnrTxId    RestrictedFINXMax16Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AcctOwnrTxId"`
	AcctSvcrTxId    RestrictedFINXMax16Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 AcctSvcrTxId,omitempty"`
	SctiesFincgTxTp SecuritiesFinancingTransactionType2Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SctiesFincgTxTp"`
	SctiesMvmntTp   ReceiveDelivery1Code                    `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 SctiesMvmntTp"`
	Pmt             DeliveryReceiptType2Code                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Pmt"`
	CmonId          RestrictedFINXMax16Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CmonId,omitempty"`
	PoolId          RestrictedFINXMax16Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 PoolId,omitempty"`
	CorpActnEvtId   RestrictedFINXMax16Text                 `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 CorpActnEvtId,omitempty"`
}

// May be one of ARNU, CCPT, CHTY, CORP, DRLC, FIIN, TXID
type TypeOfIdentification1Code string

type YieldedOrValueType1Choice struct {
	Yldd  bool                `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 Yldd"`
	ValTp PriceValueType1Code `xml:"urn:iso:std:iso:20022:tech:xsd:sese.035.002.09 ValTp"`
}

type xsdDate time.Time

func (t *xsdDate) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02")
}
func (t xsdDate) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDate) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
func _unmarshalTime(text []byte, t *time.Time, format string) (err error) {
	s := string(bytes.TrimSpace(text))
	*t, err = time.Parse(format, s)
	if _, ok := err.(*time.ParseError); ok {
		*t, err = time.Parse(format+"Z07:00", s)
	}
	return err
}
func _marshalTime(t time.Time, format string) ([]byte, error) {
	return []byte(t.Format(format + "Z07:00")), nil
}

type xsdDateTime time.Time

func (t *xsdDateTime) UnmarshalText(text []byte) error {
	return _unmarshalTime(text, (*time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalText() ([]byte, error) {
	return _marshalTime((time.Time)(t), "2006-01-02T15:04:05.999999999")
}
func (t xsdDateTime) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	if (time.Time)(t).IsZero() {
		return nil
	}
	m, err := t.MarshalText()
	if err != nil {
		return err
	}
	return e.EncodeElement(m, start)
}
func (t xsdDateTime) MarshalXMLAttr(name xml.Name) (xml.Attr, error) {
	if (time.Time)(t).IsZero() {
		return xml.Attr{}, nil
	}
	m, err := t.MarshalText()
	return xml.Attr{Name: name, Value: string(m)}, err
}
